<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_karyawan')->delete();
        DB::table('tbl_karyawan')->insert([
            [
                'nik' => '12345678',
                'nama_lengkap' => 'Tangguh Destio Pramono',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2021-05-01',
                'divisi' => 'penjualan',
                'jabatan' => 'Kepala Cabang',
                'username' => 'tangguh',
                'password' => '$2y$10$r3uZ8j/QdkpkrAylOyIOVupQ1ywm4UxiO6iNFe03WRLMKosaJTkFS',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '987654321',
                'nama_lengkap' => 'Tisya Nada Fitriana',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2021-05-01',
                'divisi' => 'penjualan',
                'jabatan' => 'Karyawan',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080720002',
                'nama_lengkap' => 'IRFAN ANGGAWIRYA',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2020-01-10',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080720009',
                'nama_lengkap' => 'WAHYUDI SATRIA',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2020-07-15',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080720015',
                'nama_lengkap' => 'RIANTI AMALIA',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2020-09-16',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'PENJUALAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080721003',
                'nama_lengkap' => 'ABU BAKAR ABROL',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2021-01-18',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080721004',
                'nama_lengkap' => 'NURDIN KODIR ZAELANI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2021-01-18',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080713044',
                'nama_lengkap' => 'YAKUB MANJARARA',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2013-01-21',
                'divisi' => 'SERVICE',
                'jabatan' => 'SERVICE ADVISOR',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080713048',
                'nama_lengkap' => 'SAHIRON',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2013-10-01',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080713051',
                'nama_lengkap' => 'ALDY KABADRIN',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2013-11-11',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080715014',
                'nama_lengkap' => 'TAUFIK HIDAYAT',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2015-03-02',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080715036',
                'nama_lengkap' => 'YORDAN BUSTAMI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2015-09-21',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080716002',
                'nama_lengkap' => 'LISA ANGGRAENI',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2016-01-21',
                'divisi' => 'SERVICE',
                'jabatan' => 'ADMIN SERVICE',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080716034',
                'nama_lengkap' => 'HERI SETIAWAN',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2016-12-02',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080716034',
                'nama_lengkap' => 'AGUSTIN NURSE .P',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2019-09-02',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080718015',
                'nama_lengkap' => 'MUHAMMAD NUR K.',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2018-05-17',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080719015',
                'nama_lengkap' => 'HARUN AR RASYID',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2019-03-20',
                'divisi' => 'SERVICE',
                'jabatan' => 'MECHANIC',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010720149',
                'nama_lengkap' => 'ALI HAMBALI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2000-09-25',
                'divisi' => 'SERVICE',
                'jabatan' => 'ADMIN SPAREPART',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010722447',
                'nama_lengkap' => 'LYDIA INDRIYANI',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2003-07-15',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES COUNT',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010723706',
                'nama_lengkap' => 'KIKI GUNAWAN',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2005-07-07',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010726828',
                'nama_lengkap' => 'SITI NURHASANAH',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2006-10-03',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES COUNT',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080712003',
                'nama_lengkap' => 'MOHAMAD ANDI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2012-01-11',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080712021',
                'nama_lengkap' => 'HERDI PRAWIRADINATA',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2012-04-02',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALESMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080712026',
                'nama_lengkap' => 'DEDE RAMLI HARYADI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2012-06-12',
                'divisi' => 'SERVICE',
                'jabatan' => 'FOREMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080712038',
                'nama_lengkap' => 'MUHAMMAD DWI IRFANSYAH',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2012-06-20',
                'divisi' => 'SERVICE',
                'jabatan' => 'SERVICE ADVISOR',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080713027',
                'nama_lengkap' => 'DARMA PREBIYANSAH',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2013-04-01',
                'divisi' => 'SERVICE',
                'jabatan' => 'FOREMAN',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010724368',
                'nama_lengkap' => 'RISE DWI .N',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2004-06-01',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'ACCOUNTING',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080717005',
                'nama_lengkap' => 'SHELLY MAULID LIANY',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2017-03-20',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'ACCOUNTING',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010727123',
                'nama_lengkap' => 'SARIMA',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2007-09-13',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'FINANCE STAFF',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080713012',
                'nama_lengkap' => 'AMANDA',
                'jenis_kelamin' => 'WANITA',
                'tgl_masuk' => '2013-03-01',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'FINANCE STAFF',
                'username' => null,
                'password' => null,
                'role' => 'karyawan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '010427033',
                'nama_lengkap' => 'HERLY BERLIANDI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2007-05-19',
                'divisi' => 'KEPALA CABANG',
                'jabatan' => 'BRANCH MANAGER',
                'username' => 'herly',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080715049',
                'nama_lengkap' => 'PRATIKNO',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2015-12-02',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES HEAD',
                'username' => 'pratikno',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080716015',
                'nama_lengkap' => 'TOMMY GHOZALI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2016-08-01',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES HEAD',
                'username' => 'tommy',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080721008',
                'nama_lengkap' => 'MUHAMAD FAUZI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2021-02-01',
                'divisi' => 'PENJUALAN',
                'jabatan' => 'SALES HEAD',
                'username' => 'fauzi',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nik' => '080700981',
                'nama_lengkap' => 'TRI BUDI',
                'jenis_kelamin' => 'PRIA',
                'tgl_masuk' => '2015-07-15',
                'divisi' => 'SERVICE',
                'jabatan' => 'SERVICE MANAGER',
                'username' => 'tribudi',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
